package com.sicd.bugmanagement.common.bean;

// Generated 2013-10-17 10:13:18 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AuthorityRole generated by hbm2java
 */
@Entity
@Table(name = "authority_role", catalog = "bugmanagement")
public class AuthorityRole implements java.io.Serializable {

	private static final long serialVersionUID = -6716817672832166414L;
	
	private Integer authorityRoleId;
	private Authority authority;
	private Role role;

	public AuthorityRole() {
	}

	public AuthorityRole(Authority authority, Role role) {
		this.authority = authority;
		this.role = role;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "authority_role_id", unique = true, nullable = false)
	public Integer getAuthorityRoleId() {
		return this.authorityRoleId;
	}

	public void setAuthorityRoleId(Integer authorityRoleId) {
		this.authorityRoleId = authorityRoleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "authority_id")
	public Authority getAuthority() {
		return this.authority;
	}

	public void setAuthority(Authority authority) {
		this.authority = authority;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

}
