package com.sicd.bugmanagement.common.bean;

// Generated 2013-10-17 10:13:18 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bug generated by hbm2java
 */
@Entity
@Table(name = "bug", catalog = "bugmanagement")
public class Bug implements java.io.Serializable {

	private static final long serialVersionUID = -3093239599396988403L;
	
	private Integer bugId;
	private Developer assignedTo;
	private User creator;
	private Module module;
	private UserCase fromCase;
	private UserCase toCase;
	private Bug relatedBug;
	private String title;
	private Integer priority;
	private String steps;
	private Date createdAt;
	private String status;
	private String os;
	private String browser;
	private String type;
	private Integer severity;
	private String keyword;
	private Boolean confirm;
	private String resolution;
	private String mailto;
	private Set<Bug> bugs = new HashSet<Bug>(0);
	private Set<AffectedVersion> affectedVersions = new HashSet<AffectedVersion>(
			0);
	private Set<UserCase> userCasesForToBug = new HashSet<UserCase>(0);
	private Set<UserCase> userCasesForFromBug = new HashSet<UserCase>(0);

	public Bug() {
	}

	public Bug(Developer developer, User user, Module module,
			UserCase fromCase, UserCase toCase, Bug bug,
			String title, Integer priority, String steps, Date createdAt,
			String status, String os, String browser, String type,
			Integer severity, String keyword, Boolean confirm, Set<Bug> bugs,
			Set<AffectedVersion> affectedVersions,
			Set<UserCase> userCasesForToBug, Set<UserCase> userCasesForFromBug) {
		this.assignedTo = developer;
		this.creator = user;
		this.module = module;
		this.fromCase = fromCase;
		this.toCase = toCase;
		this.relatedBug = bug;
		this.title = title;
		this.priority = priority;
		this.steps = steps;
		this.createdAt = createdAt;
		this.status = status;
		this.os = os;
		this.browser = browser;
		this.type = type;
		this.severity = severity;
		this.keyword = keyword;
		this.confirm = confirm;
		this.bugs = bugs;
		this.affectedVersions = affectedVersions;
		this.userCasesForToBug = userCasesForToBug;
		this.userCasesForFromBug = userCasesForFromBug;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "bugID", unique = true, nullable = false)
	public Integer getBugId() {
		return this.bugId;
	}

	public void setBugId(Integer bugId) {
		this.bugId = bugId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "assigned_to")
	public Developer getAssignedTo() {
		return this.assignedTo;
	}

	public void setAssignedTo(Developer assignedTo) {
		this.assignedTo = assignedTo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "module_id")
	public Module getModule() {
		return this.module;
	}

	public void setModule(Module module) {
		this.module = module;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "from_case")
	public UserCase getFromCase() {
		return this.fromCase;
	}

	public void setFromCase(UserCase fromCase) {
		this.fromCase = fromCase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "to_case")
	public UserCase getToCase() {
		return this.toCase;
	}

	public void setToCase(UserCase toCase) {
		this.toCase = toCase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "related_bug")
	public Bug getRelatedBug() {
		return this.relatedBug;
	}

	public void setRelatedBug(Bug relatedBug) {
		this.relatedBug = relatedBug;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "priority")
	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	@Column(name = "steps", length = 65535)
	public String getSteps() {
		return this.steps;
	}

	public void setSteps(String steps) {
		this.steps = steps;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "status", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "os", length = 20)
	public String getOs() {
		return this.os;
	}

	public void setOs(String os) {
		this.os = os;
	}

	@Column(name = "browser", length = 30)
	public String getBrowser() {
		return this.browser;
	}

	public void setBrowser(String browser) {
		this.browser = browser;
	}

	@Column(name = "type", length = 30)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "severity")
	public Integer getSeverity() {
		return this.severity;
	}

	public void setSeverity(Integer severity) {
		this.severity = severity;
	}

	@Column(name = "keyword")
	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	@Column(name = "confirm")
	public Boolean getConfirm() {
		return this.confirm;
	}

	public void setConfirm(Boolean confirm) {
		this.confirm = confirm;
	}
	
	@Column(name = "resolution")
	public String getResolution() {
		return resolution;
	}

	public void setResolution(String resolution) {
		this.resolution = resolution;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "creator")
	public User getCreator() {
		return creator;
	}

	public void setCreator(User creator) {
		this.creator = creator;
	}
	
	@Column(name = "mailto", length = 255)
	public String getMailto() {
		return mailto;
	}

	public void setMailto(String mailto) {
		this.mailto = mailto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "relatedBug")
	public Set<Bug> getBugs() {
		return this.bugs;
	}

	public void setBugs(Set<Bug> bugs) {
		this.bugs = bugs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bug")
	public Set<AffectedVersion> getAffectedVersions() {
		return this.affectedVersions;
	}

	public void setAffectedVersions(Set<AffectedVersion> affectedVersions) {
		this.affectedVersions = affectedVersions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "toBug")
	public Set<UserCase> getUserCasesForToBug() {
		return this.userCasesForToBug;
	}

	public void setUserCasesForToBug(Set<UserCase> userCasesForToBug) {
		this.userCasesForToBug = userCasesForToBug;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fromBug")
	public Set<UserCase> getUserCasesForFromBug() {
		return this.userCasesForFromBug;
	}

	public void setUserCasesForFromBug(Set<UserCase> userCasesForFromBug) {
		this.userCasesForFromBug = userCasesForFromBug;
	}

}
