package com.sicd.bugmanagement.common.bean;

// Generated 2013-10-17 10:13:18 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Dictionary generated by hbm2java
 */
@Entity
@Table(name = "dictionary", catalog = "bugmanagement")
public class Dictionary implements java.io.Serializable {

	private static final long serialVersionUID = 1086379009095470374L;
	
	private Integer dictionaryId;
	private String dictionaryKey;
	private String dictionaryValue;
	private String dictionaryDescribe;
	private String locationTable;

	public Dictionary() {
	}

	public Dictionary(String dictionaryKey, String dictionaryValue,
			String dictionaryDescribe, String locationTable) {
		this.dictionaryKey = dictionaryKey;
		this.dictionaryValue = dictionaryValue;
		this.dictionaryDescribe = dictionaryDescribe;
		this.locationTable = locationTable;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "dictionary_id", unique = true, nullable = false)
	public Integer getDictionaryId() {
		return this.dictionaryId;
	}

	public void setDictionaryId(Integer dictionaryId) {
		this.dictionaryId = dictionaryId;
	}

	@Column(name = "dictionary_key")
	public String getDictionaryKey() {
		return this.dictionaryKey;
	}

	public void setDictionaryKey(String dictionaryKey) {
		this.dictionaryKey = dictionaryKey;
	}

	@Column(name = "dictionary_value")
	public String getDictionaryValue() {
		return this.dictionaryValue;
	}

	public void setDictionaryValue(String dictionaryValue) {
		this.dictionaryValue = dictionaryValue;
	}

	@Column(name = "dictionary_describe")
	public String getDictionaryDescribe() {
		return this.dictionaryDescribe;
	}

	public void setDictionaryDescribe(String dictionaryDescribe) {
		this.dictionaryDescribe = dictionaryDescribe;
	}

	@Column(name = "location_table", length = 30)
	public String getLocationTable() {
		return this.locationTable;
	}

	public void setLocationTable(String locationTable) {
		this.locationTable = locationTable;
	}

}
