package com.sicd.bugmanagement.common.bean;

// Generated 2013-10-17 10:13:18 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ExcludeException generated by hbm2java
 */
@Entity
@Table(name = "exclude_exception", catalog = "bugmanagement")
public class ExcludeException implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer excludeId;
	private Developer developer;
	private MyException myException;
	private Date createdAt;

	public ExcludeException() {
	}

	public ExcludeException(Developer developer, MyException myException,
			Date createdAt) {
		this.developer = developer;
		this.myException = myException;
		this.createdAt = createdAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "exclude_id", unique = true, nullable = false)
	public Integer getExcludeId() {
		return this.excludeId;
	}

	public void setExcludeId(Integer excludeId) {
		this.excludeId = excludeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "developer_id")
	public Developer getDeveloper() {
		return this.developer;
	}

	public void setDeveloper(Developer developer) {
		this.developer = developer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "exception_id")
	public MyException getMyException() {
		return this.myException;
	}

	public void setMyException(MyException myException) {
		this.myException = myException;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

}
