package com.sicd.bugmanagement.common.bean;

// Generated 2013-10-17 10:13:18 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MailTemplate generated by hbm2java
 */
@Entity
@Table(name = "mail_template", catalog = "bugmanagement")
public class MailTemplate implements java.io.Serializable {

	private static final long serialVersionUID = 3734371775522852687L;
	
	private Integer mailTemplateId;
	private String mailType;
	private String mailSubject;
	private String mailContent;

	public MailTemplate() {
	}

	public MailTemplate(String mailType, String mailSubject, String mailContent) {
		this.mailType = mailType;
		this.mailSubject = mailSubject;
		this.mailContent = mailContent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "mail_template_id", unique = true, nullable = false)
	public Integer getMailTemplateId() {
		return this.mailTemplateId;
	}

	public void setMailTemplateId(Integer mailTemplateId) {
		this.mailTemplateId = mailTemplateId;
	}

	@Column(name = "mail_type")
	public String getMailType() {
		return this.mailType;
	}

	public void setMailType(String mailType) {
		this.mailType = mailType;
	}

	@Column(name = "mail_subject")
	public String getMailSubject() {
		return this.mailSubject;
	}

	public void setMailSubject(String mailSubject) {
		this.mailSubject = mailSubject;
	}

	@Column(name = "mail_content", length = 65535)
	public String getMailContent() {
		return this.mailContent;
	}

	public void setMailContent(String mailContent) {
		this.mailContent = mailContent;
	}

}
