package com.sicd.bugmanagement.common.bean;

// Generated 2013-10-17 10:13:18 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Module generated by hbm2java
 */
@Entity
@Table(name = "module", catalog = "bugmanagement")
public class Module implements java.io.Serializable {

	private static final long serialVersionUID = 5274739263029759587L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "module_id", unique = true, nullable = false)
	private Integer moduleId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id")
	private Project project;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_id")
	private Module parent;

	@Column(name = "name")
	private String name;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	private Date createdAt;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parent")
	private Set<Module> children = new HashSet<Module>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "module")
	private Set<UserCase> userCases = new HashSet<UserCase>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "module")
	private Set<Bug> bugs = new HashSet<Bug>(0);

	public Module() {
	}

	public Module(Project project, Module parent, String name,
			Set<Module> children, Set<UserCase> userCases, Set<Bug> bugs) {
		this.project = project;
		this.parent = parent;
		this.name = name;
		this.children = children;
		this.userCases = userCases;
		this.bugs = bugs;
	}

	public Integer getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(Integer moduleId) {
		this.moduleId = moduleId;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public void setParent(Module parent) {
		this.parent = parent;
	}

	public Module getParent() {
		return parent;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Set<Module> getChildren() {
		return children;
	}

	public void setChildren(Set<Module> children) {
		this.children = children;
	}

	public Set<UserCase> getUserCases() {
		return this.userCases;
	}

	public void setUserCases(Set<UserCase> userCases) {
		this.userCases = userCases;
	}

	public Set<Bug> getBugs() {
		return this.bugs;
	}

	public void setBugs(Set<Bug> bugs) {
		this.bugs = bugs;
	}

}
