package com.sicd.bugmanagement.common.bean;

// Generated 2013-10-17 10:13:18 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Exception generated by hbm2java
 */
@Entity
@Table(name = "exception", catalog = "bugmanagement")
public class MyException implements java.io.Serializable {

	private static final long serialVersionUID = 4485741395073469475L;
	
	private Integer exceptionId;
	private String exceptionClass;
	private String category;
	private String description;
	private Set<Question> questions = new HashSet<Question>(0);
	private Set<ExceptionRecord> exceptionRecords = new HashSet<ExceptionRecord>(
			0);
	private Set<ExcludeException> excludeExceptions = new HashSet<ExcludeException>(
			0);

	public MyException() {
	}

	public MyException(String exceptionClass, String exceptionMsg,
			Set<Question> questions, Set<ExceptionRecord> exceptionRecords,
			Set<ExcludeException> excludeExceptions) {
		this.exceptionClass = exceptionClass;
		this.description = exceptionMsg;
		this.questions = questions;
		this.exceptionRecords = exceptionRecords;
		this.excludeExceptions = excludeExceptions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "exception_id", unique = true, nullable = false)
	public Integer getExceptionId() {
		return this.exceptionId;
	}

	public void setExceptionId(Integer exceptionId) {
		this.exceptionId = exceptionId;
	}

	@Column(name = "exception_class")
	public String getExceptionClass() {
		return this.exceptionClass;
	}

	public void setExceptionClass(String exceptionClass) {
		this.exceptionClass = exceptionClass;
	}
	
	
	@Column(name = "category", length = 255)
	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "myException")
	public Set<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set<Question> questions) {
		this.questions = questions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "myException")
	public Set<ExceptionRecord> getExceptionRecords() {
		return this.exceptionRecords;
	}

	public void setExceptionRecords(Set<ExceptionRecord> exceptionRecords) {
		this.exceptionRecords = exceptionRecords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "myException")
	public Set<ExcludeException> getExcludeExceptions() {
		return this.excludeExceptions;
	}

	public void setExcludeExceptions(Set<ExcludeException> excludeExceptions) {
		this.excludeExceptions = excludeExceptions;
	}

}
