package com.sicd.bugmanagement.common.bean;

// Generated 2013-10-17 10:13:18 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Resource generated by hbm2java
 */
@Entity
@Table(name = "resource", catalog = "bugmanagement")
public class Resource implements java.io.Serializable {

	private static final long serialVersionUID = 6762738735476581368L;
	
	private Integer resourceId;
	private Integer objectId;
	private String objectType;
	private String resourceUrl;
	private String resourceName;

	public Resource() {
	}

	public Resource(Integer objectId, String objectType, String resourceUrl,
			String resourceName) {
		this.objectId = objectId;
		this.objectType = objectType;
		this.resourceUrl = resourceUrl;
		this.resourceName = resourceName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "resource_id", unique = true, nullable = false)
	public Integer getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(Integer resourceId) {
		this.resourceId = resourceId;
	}

	@Column(name = "object_id")
	public Integer getObjectId() {
		return this.objectId;
	}

	public void setObjectId(Integer objectId) {
		this.objectId = objectId;
	}

	@Column(name = "object_type", length = 30)
	public String getObjectType() {
		return this.objectType;
	}

	public void setObjectType(String objectType) {
		this.objectType = objectType;
	}

	@Column(name = "resource_url")
	public String getResourceUrl() {
		return this.resourceUrl;
	}

	public void setResourceUrl(String resourceUrl) {
		this.resourceUrl = resourceUrl;
	}

	@Column(name = "resource_name")
	public String getResourceName() {
		return this.resourceName;
	}

	public void setResourceName(String resourceName) {
		this.resourceName = resourceName;
	}

}
