package com.sicd.bugmanagement.common.bean;

// Generated 2013-10-17 10:13:18 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Step generated by hbm2java
 */
@Entity
@Table(name = "step", catalog = "bugmanagement")
public class Step implements java.io.Serializable {

	private static final long serialVersionUID = 5197337696572053960L;
	
	private Integer stepId;
	private UserCase userCase;
	private Integer num;
	private String content;
	private String expect;
	private String result;
	private String reality;

	public Step() {
	}

	public Step(UserCase userCase, Integer num, String content, String expect,
			String result, String reality) {
		this.userCase = userCase;
		this.num = num;
		this.content = content;
		this.expect = expect;
		this.result = result;
		this.reality = reality;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "step_id", unique = true, nullable = false)
	public Integer getStepId() {
		return this.stepId;
	}

	public void setStepId(Integer stepId) {
		this.stepId = stepId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "case_id")
	public UserCase getUserCase() {
		return this.userCase;
	}

	public void setUserCase(UserCase userCase) {
		this.userCase = userCase;
	}

	@Column(name = "num")
	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "expect", length = 65535)
	public String getExpect() {
		return this.expect;
	}

	public void setExpect(String expect) {
		this.expect = expect;
	}

	@Column(name = "result", length = 30)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	@Column(name = "reality", length = 65535)
	public String getReality() {
		return this.reality;
	}

	public void setReality(String reality) {
		this.reality = reality;
	}

}
