package com.sicd.bugmanagement.common.bean;

// Generated 2013-10-17 10:13:18 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TestCase generated by hbm2java
 */
@Entity
@Table(name = "test_case", catalog = "bugmanagement")
public class TestCase implements java.io.Serializable {

	private static final long serialVersionUID = -3111850034763101642L;
	
	private Integer testCaseId;
	private UserCase userCase;
	private Task task;

	public TestCase() {
	}

	public TestCase(UserCase userCase, Task task) {
		this.userCase = userCase;
		this.task = task;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "test_case_id", unique = true, nullable = false)
	public Integer getTestCaseId() {
		return this.testCaseId;
	}

	public void setTestCaseId(Integer testCaseId) {
		this.testCaseId = testCaseId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "case_id")
	public UserCase getUserCase() {
		return this.userCase;
	}

	public void setUserCase(UserCase userCase) {
		this.userCase = userCase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "task_id")
	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

}
