'use strict';StackExchange.tagEditor=function(d,q,r){function s(){i=!0}function O(){if("undefined"===typeof x){for(var a=StackExchange.tagEditor.requiredTags,b=[],e=0;e<a.length;e++)b.push(a[e].Name.replace(/[.+]/g,"\\$&"));x=RegExp("^(?:"+b.join("|")+")$")}return x}function H(){if(StackExchange.tagEditor.requiredTags&&/^ ?$/.test(c.val())){var a=O();0===g.add(h).children().filter(function(){return a.test($(this).text())}).length&&I(StackExchange.tagEditor.requiredTags)}}function t(a,b){var e=window.tagRendererRaw(a,
null,"span"),e=$(e);b||(e.append($("<span>",{"class":"delete-tag",title:"remove this tag"})),f.trigger("tagSpanCreated",[e]));return e}function J(){var a=g.find(".post-tag").map(function(a,b){return $(b).text()}).get().join(" ");a.length&&(a+=" ");var b=h.find(".post-tag").map(function(a,b){return $(b).text()}).get().join(" ");b.length&&c.val().length&&(b=" "+b);return{text:a+c.val()+b,lengthBeforeInput:a.length}}function y(){var a=c.caret();if(g.add(h).find(".post-tag").length){var b=J();c.val(b.text);
g.empty();h.empty();c.caret(a.start+b.lengthBeforeInput,a.end+b.lengthBeforeInput);o()}}function l(a){if(!p){var b;b=a?{start:c.val().length,end:c.val().length}:c.caret();-1==b.start&&(b.start=b.end=0);if(b.start!==b.end)y();else{a=c.val().substr(0,b.start);b=c.val().substr(b.start);a=(a+"!").split(/[,;\s]+/);a[a.length-1]="!"===a[a.length-1]?"":a[a.length-1].slice(0,-1);var e=b.split(/[,;\s]+/),j=a.pop();b=j.length;var j=j+e.shift(),a=sanitizeAndSplitTags(a.join(" ")),e=sanitizeAndSplitTags(e.join(" ")),
k;for(k=0;k<a.length;k++)t(a[k]).appendTo(g);for(k=0;k<e.length;k++)t(e[k]).appendTo(h);j!==c.val()&&c.val(j);f.find(".post-tag").filter(function(){return/^\s*$/.test($(this).text())}).remove();a=J().text;a!=d.val()&&d.val(a).trigger("change");i&&(c.caret(b,b),P(),H())}Q()}}function m(a,b){var e,j;if("string"===typeof a)j=a;else if(a.length)e=a,j=e.text();else return;for(var k=sanitizeAndSplitTags(c.val()),d=0;d<k.length;d++)t(k[d]).appendTo(g);c.val(j);e?(j=$($.unique(e.prevAll(".post-tag").get())),
e.nextAll(".post-tag").prependTo(h),j.appendTo(g),e.remove()):h.find(".post-tag").appendTo(g);c.focus();b&&c.caret(0,0)}function K(a){a!==u&&(g.add(c).add(h).css({position:"relative",left:a}),u=a)}function Q(){var a;var b=c;a="c_"+b.val();if(a in z)a=z[a];else{var e=$("<span />").css("font-family",b.css("font-family"));e.text(b.val());e.insertAfter(b);b=e.innerWidth();e.remove();a=z[a]=b}a+=19;e=g.outerWidth();h.children().length||(a=Math.max(a,n-e-8));c.css("width",a);0<e+u&&e+u+a<n||(e+a<n?K(0):
K(-e+(n-a)/2))}function L(){A=!0;setTimeout(function(){A=!1},0)}function R(a){var b=a.find("p.more-info");"undefined"===typeof B&&(B=M-5-b.outerWidth());a.find(".post-tag:first").outerWidth()+a.find(".item-multiplier").outerWidth()>B&&b.find("a").text("info")}function I(a,b){$(".tag-suggestions").remove();p=!1;var e=a.length;if(0!==e){for(var c=$("<div class='tag-suggestions' />").css({position:"absolute",left:f.position().left,top:f.position().top+C+1,width:n-10}).insertAfter(f),d=0;d<a.length;d++){var g=
S(a[d],b).appendTo(c).attr("tabindex",D||0);R(g);0===d%3&&g.css("clear","both")}c.delegate("div","keydown",T);c.delegate("div","click",function(a){$(a.target).is("a")||E($(this))});c.delegate("div","focus",function(){A&&1===e?E($(this)):p=!0});c.delegate("div","blur",function(){p=!1})}}function P(){var a=sanitizeAndSplitTags(c.val())[0];F!==a&&(F=a,!a||!a.length?o():U(a,function(b){a===F&&i&&I(b,a)}))}function S(a,b){var c=$("<div />").css("width",M).data("tag-name",a.SynonymOf||a.Name);b&&(b=b.replace(/-/g,
"").replace(/(.)(?=.)/g,"$1-*").replace(/\+/g,"\\+").replace(/\./g,"\\."));var d=t(a.Name,!0),f=d.html();b&&(f=f.replace(RegExp("("+b+")"),"<span class='match'>$1</span>"));c.append(d.html(f));a.Count&&c.append($("<span class='item-multiplier' />").html("&times;&nbsp;"+a.Count));d="";a.Excerpt&&(d=a.Excerpt);d.length&&c.append($("<p />").text(d));if(a.Synonyms&&a.Synonyms.length)for(var f=$("<p >also:</p>").appendTo(c),g=a.Synonyms.split(/\|/),h=0;h<g.length;h++)d=g[h],b&&(d=d.replace(RegExp("("+
b+")"),"<span class='match'>$1</span>")),0<h&&(d=", "+d),f.append("<span>"+d+"</span>");c.append("<p class='more-info'><a href='/tags/"+encodeURIComponent(a.SynonymOf||a.Name)+"/info' target='_blank'>learn more</a></p>");return c}function U(a,b){G["t_"+a]?b(G["t_"+a]):N.trigger(a,b)}function E(a){c.val(a.data("tag-name"));o();m("");l()}function o(){$(".tag-suggestions").remove();p=!1;N.cancel()}function T(a){switch(a.which){case 39:case 40:return $(this).next("div").focus(),!1;case 37:return $(this).prev("div").focus(),
!1;case 38:return a=$(this).prev("div"),a.length?a.focus():c.focus(),!1;case 27:return o(),c.focus(),!1;case 13:case 32:return E($(this)),!1}}var i;if("undefined"===typeof r)try{i=d.is(":focus")}catch(W){i=!1}else i=r;d.bind("focus",s);if(d.is(":visible")){d.unbind("focus",s);var n=d.innerWidth(),M=(n-40)/3|0,f=$("<div class='tag-editor' />").css("width",n).insertAfter(d);d.hide();var r=$("<span class='post-tag'>test</span>").appendTo(f),C=f.innerHeight();r.remove();f.css("height",C);var g=$("<span />").appendTo(f),
c=$("<input type='text' tabIndex='0'/>").appendTo(f).val(d.val()+" "),h=$("<span />").appendTo(f),D=d.attr("tabIndex");D&&c.attr("tabIndex",D);var p=!1,x,v=i;c.focus(function(a,b){i=!0;H();v||(b||d.triggerHandler("focus",!0),v=!0)});var w=!1;f.mousedown(function(){w=!0;$(document).one("mouseup",function(){setTimeout(function(){i||(d.triggerHandler("blur"),v=!1);w=!1},0)})});c.blur(function(){i=!1;setTimeout(function(){p||(o(),l(),w||(d.triggerHandler("blur"),v=!1));w=!1},0)});d.focus(function(a,b){b||
c.trigger("focus",!0)});c.keydown(function(a){if(a.shiftKey&&V[a.which]||a.ctrlKey&&65===a.which)return y(),!0;var b=c.caret().start,d=b===c.val().length,f=0===b;switch(a.which){case 37:if(!f)break;m(g.find(".post-tag:last"));return!1;case 39:if(!d)break;m(h.find(".post-tag:first"),!0);return!1;case 8:if(!f)break;a=g.find(".post-tag:last");if(!a.length)return;c.val(a.text()+c.val());c.caret(a.text().length+b);a.remove();return!1;case 46:if(!d)break;a=h.find(".post-tag:first");if(!a.length)return;
c.val(c.val()+a.text());c.caret(b,b);a.remove();return!1;case 36:a=g.find(".post-tag:first");if(!a.length)break;m(a,!0);return!1;case 35:a=h.find(".post-tag:last");if(!a.length)break;m(a);return!1;case 40:return L(),$(".tag-suggestions > div:first").focus(),!1;case 9:L();break;case 27:o();break;case 13:if($(".tag-suggestions").length)return!1}return!0});c.bind("keydown paste click change",function(){setTimeout(function(){l()},0)});f.delegate(".post-tag","click",function(a){var b=$(this);$(a.target).hasClass("delete-tag")&&
b.text("");m(b);l()});f.click(function(a){a.target===this&&(m(""),l())});f.on("rerender",function(){y();l(!0)});var z={},u=0,V={35:!0,36:!0,37:!0,38:!0,39:!0,40:!0},A,F,B,G={},N=StackExchange.helpers.DelayedReaction(function(a,b){StackExchange.helpers.addSpinner(f,{position:"absolute",right:10,top:C/2-2});$.get("/filter/tags",{q:a,newstyle:!0},"json").done(function(c){G["t_"+a]=c;StackExchange.helpers.removeSpinner();b(c)})},400,{sliding:!0});l(!0);StackExchange.helpers.genericBindOverlayEvents(f,
c,function(){var a=c.val();return(""===a||" "===a)&&0===g.add(h).children().filter(function(){return!/^\s*$/.test($(this).text())}).length});StackExchange.tagEditor.ready.resolve();d[0].func_clear=function(){d.val("");c.val("").blur();f.find(".post-tag").remove()};d[0].func_add=function(a){var b=c.val();c.val(a);m(b);l()}}else q=q||0,3>q?setTimeout(function(){d.unbind("focus",s);StackExchange.tagEditor(d,q+1,i)},300):(d.unbind("focus",s),$("body.review-task-page").length||StackExchange.debug.log("tag box is invisible, couldn't start tag editor"))};
StackExchange.tagEditor.ready=$.Deferred();